version: '3.3'
services:
  mysql_db_api:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'career-9'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'Career-qCsfeuECc3MW'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'Career-qCsfeuECc3MW'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - career_shared_net

    #   api-mysql:

  # api:
  #   build:
  #     context: ./spring-social
  #     dockerfile: dockerfile
  #   ports:
  #     - 8080:8080
  #   command: ["java","-jar","/usr/local/lib/demo.jar"]  
       # restart: always
    # networks:
    #   api-mysql:


  # front-end:
  #   container_name: front-end-api
  #   image: front-end-api-img
  #   build:
  #     context: ./react-social
  #     dockerfile: dockerfile
  #   ports:
  #     - 3000:3000
  #   restart: always  
# Names our volume
volumes:
  mysql_data:

networks:
  career_shared_net:
    external: true
