version: '3.3'
services:
  mysql_db_api:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'career-9'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'Career-qCsfeuECc3MW'
      MYSQL_ROOT_PASSWORD: 'Career-qCsfeuECc3MW'
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-custom.cnf:/etc/mysql/conf.d/custom.cnf
    deploy:
      resources:
        limits:
          memory: 3g
    networks:
      - career_shared_net

  api:
    build:
      context: ./spring-social
      dockerfile: dockerfile
    ports:
      - 8080:8080
    command: ["java", "-Xms2g", "-Xmx4g", "-jar", "/usr/local/lib/demo.jar"]
    restart: always
    env_file:
      - .env
    deploy:
      resources:
        limits:
          memory: 4g
    depends_on:
      - mysql_db_api
    networks:
      - career_shared_net

volumes:
  mysql_data:

networks:
  career_shared_net:
    external: true